version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=youLearning
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ibm.com
      - PGADMIN_DEFAULT_PASSWORD=admin4321
    ports:
    - 8080:80 